---
title: "Graph Generator"
output: pdf_document
date: "2026-01-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Connect this into JSON files

## This document shows how to use functions and apply it to data for various graphs

## You can automatically extract the columns right from excel (category.year).... losing this functionality for now

```{r}

library(tidyverse)
library(jsonlite)

## Lets test with one year for now -
wincap <- read.csv("Employee_2001.csv")

## This is the problem......

## years <- 2001:2026 ## Set years

## Employee.Info <- setNames(
  ## lapply(years, function(y) {
   ##  read.csv(paste0("Employee_", y, ".csv"))
 ##  }), years)

json_data <- fromJSON("Graphs.json")

```

## Extract the column
```{r}

Job.Title <- wincap$Job.Title.2001
variable_map <- list(
  Job.Title = data.frame(Job.Title = Job.Title)  # ggplot needs a data frame
)

```


## Graph Generator Function
```{r}

## The column name in excel has to have this format (category.year)

plot_employee_data <- function(data, top_n = 10, x_label = NULL, title_label = NULL) {
  
  col_name <- colnames(data)[1]  # get column name dynamically
  
  count_df <- data %>%
    filter(!is.na(.data[[col_name]])) %>%
    count(.data[[col_name]]) %>%
    slice_max(n, n = top_n)
  
  ggplot(count_df, aes(x = fct_reorder(.data[[col_name]], n, .desc = TRUE), y = n)) +
    geom_col(fill = "steelblue") +
    coord_flip() +
    labs(
      x = ifelse(is.null(x_label), col_name, x_label),
      y = "Number of Employees",
      title = ifelse(is.null(title_label), paste("Number of Employees by", col_name), title_label)
    )
}

```

```{r}

function_map <- list(
  plot_employee_data = plot_employee_data
)

func_name <- json_data[["function"]]
arg_name  <- json_data$arguments$x

func <- function_map[[func_name]]
arg  <- variable_map[[arg_name]]

# Call the function
result_plot <- do.call(func, list(data = arg))
print(result_plot)

```


